{{- if and (not .Values.secrets.existingSecret) .Values.secrets.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nunmai.secretName" . }}
  labels: {{- include "nunmai.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
